apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.fullname" . }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
type: Opaque
data:
  datasource-url: {{ .Values.secrets.datasourceUrl | b64enc | quote }}
  datasource-username: {{ .Values.secrets.datasourceUsername | b64enc | quote }}
  datasource-password: {{ .Values.secrets.datasourcePassword | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
